# https://github.com/containous/traefik/releases
traefik_version: 2.4.2

traefik_name: "traefik"
traefik_bin_path: "/usr/local/bin/{{ traefik_name }}"

traefik_data_dir: "/var/lib/{{ traefik_name }}"
traefik_dynamic_dir: "{{ traefik_data_dir }}/dynamic"

traefik_config_path: "{{ traefik_data_dir }}/traefik.yml"
traefik_acme_path: "{{ traefik_data_dir }}/acme.json"

traefik_log_path: /var/log/traefik.log
traefik_access_log_path: /var/log/traefik-access.log

traefik_letsencrypt_cf_dns_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31393833636436623936666265646237623536353961353936666638636364313762393766323431
  3532633339643634643435383030653164383564366565360a623432373239653635393532626331
  63613261333136313866653566313363613831313435353165616332663530326431343138376632
  6337343932333061320a373334633833643862626362636535316461313362346233336135393165
  34643439323963663432363836383965373065613535363163663837306431343936376435343533
  3161323634376336306138613831323862383932363633363737
traefik_letsencrypt_cf_zone_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38376232386334653433623863626530346335636561653464636433613937623834616664653762
  3432346330613330666138396332353532346131353530350a366361656334666462623263326261
  33333934633534396235656636656433666336626330343063633034316164303365663030653939
  3333643665633839380a393466653834346263626230633731393934626338366138326664643136
  66383531363063313261373333663237663134373766626364646262386562616266373739653232
  3664323633663237643039623439353034323639303231333535

# Records must also be created in terraform/cloudflare to point here
traefik_domain_main: home.lingrino.dev
