name: Serverless - Validate

on:
  workflow_dispatch:
  push:
    paths:
      - serverless/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # https://golang.org/dl/
      - name: Go Format
        run: test -z $(gofmt -l -w -s .)
      - name: Lint AMI Cleaner
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: v1.36 # https://github.com/golangci/golangci-lint/releases
          working-directory: ./serverless/ami-cleaner
      - name: Lint SNS Notifier
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          version: v1.36 # https://github.com/golangci/golangci-lint/releases
          working-directory: ./serverless/sns-notifier
